name: CI Pipeline for FlipBird

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint sphinx pre-commit

      - name: Run unit tests
        run: python -m unittest discover -s tests

      - name: Run Pylint
        run: pylint src/*.py

      - name: Generate Documentation with Sphinx
        run: |
          sphinx-apidoc -o source .
          sphinx-build -b html source build

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/build
